services:
  - type: web
    name: bn-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/offres
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        value: 7364954180
      - key: TELEGRAM_ENABLED
        value: true
